---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update-cache: yes


  - name: install apache2 package
    apt:
      name: apache2
      state: lastest


  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: lastest

